version: "3.8"

services:
  gunicorn:
    container_name: gunicorn
    image: ahmadhr/klevernet:klevernet_2.0
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - CELERY_BACKEND=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - db
    restart: always
    volumes:
      - shared-static:/opt/app/static/
      - shared-media:/opt/app/media/
    

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'


  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - gunicorn
      
    volumes:
      - shared-static:/opt/app/static/
      - shared-media:/opt/app/media/


  celery:
    image: ahmadhr/klevernet:klevernet_2.0
    command: celery -A engine worker -l INFO --loglevel=info
    depends_on:
      - redis

  db:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_PORT=5432



volumes:
  shared-static:
  shared-media: