version: "3.8"

services:
  gunicorn:
    image: ahmadhr/netsmart:klevernet
    ports:
      - "8000:8000"
    environment:
      - CELERY_BACKEND='redis://redis:6379/3'
      - CELERY_BROKER_URL='redis://redis:6379/4'
      - CELERY_RESULT_BACKEND='redis://redis:6379/5'
    depends_on:
      - db
      - redis
    volumes:
      - ./static:/static
      - ./media:/media
    restart: always
    command: python manage.py runserver 0.0.0.0:8000 --insecure

  db:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_PORT=5432

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - gunicorn
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx_log:/var/log/nginx


  celery:
    build: .
    image: celery
    command:
      - celery worker --app=core --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./app:/app

  celery-beat:
    build: .
    image: celery
    command: celery -A core beat -l info
    depends_on:
      - redis


  redis:
    image: "redis:alpine"


volumes:
  static:
  media:
  nginx_log:

